### ISSUE TITLE
Replacing a selection with a quote mark doesn't collapse the selection

### ISSUE THREAD

**Issue by joeltg** [pubpub/pubpub-editor#20]
Okay so

If text is currently selected, and a letter is pressed, the text selection is replaced by that letter (correctly). However, if text is currently selected and a quote mark is inserted (either a single quote or a double quote using shift), the text will be replaced by the quote mark **but the selection will not be collapsed**. The quote mark that gets inserted will be selected, and if further keys are pressed then that quote mark will get replaced as a result.

**Comment by isTravis** [comment]
Wow - that's pretty surprising. It looks like it's happening on the [default Prosemirror example too](https://prosemirror.net/examples/basic/). Likely something that could be filed as an issue on [Prosemirror issues](https://github.com/ProseMirror/prosemirror/issues).

@idreyn, would you mind poking in `prosemirror-inputrules` and `prosemirror-keymap` to see if there is an obvious PR?

**Comment by idreyn** [comment]
Sure enough, it's one of the input rules:
```
export const openDoubleQuote = new InputRule(/(?:^|[\s\{\[\(\<'"\u2018\u201C])(")$/, "“")
```
The problem is actually quite general. When Prosemirror sees a plugin with a `handleTextInput` prop that returns a replacement for a given piece of text, the code lets that plugin fire a transaction, _rather_ than creating a transaction that resolves the selection as expected. Ideally, we'd like it to do both.

Given the huge number of interactions that might depend on this behavior, I don't feel confident that I can open a PR to `prosemirror-view` that can resolve this to everyone's satisfaction. Maybe Marijn will have more to say about it if I open an issue over there.

_EDIT:_ Hmm, this might be solvable with a PR to `prosemirror-inputrules`.

**Comment by idreyn** [comment]
Our guy Marijn pushed a fix for this last night and I brought it into the `v6` branch as of 29efc4a.
